name: Mocha Tests
on: 
  push:
    branches: [ main ]
    paths:
    - '**.ts'
    - '**.json'
  pull_request:
    branches: [ main ]
    paths:
    - '**.ts'
    - '**.json'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Running tests
      run: yarn test
